// Comprehensive statutory payroll data for SG, HK, MY — March 2026 baseline

export type Jurisdiction = "SG" | "HK" | "MY";
export type Status = "RED" | "AMBER" | "GREEN";
export type ChangeType = "rate_change" | "threshold_change" | "new_rule" | "abolished" | "filing_change" | "system_change" | "no_change";
export type ConfidenceTier = "Tier 1" | "Tier 2" | "Tier 3";

export interface StatutoryItem {
  id: string;
  jurisdiction: Jurisdiction;
  category: string;
  subcategory: string;
  name: string;
  status: Status;
  description: string;
  currentValue: string;
  previousValue: string | null;
  changeType: ChangeType;
  effectiveDate: string;
  confidenceTier: ConfidenceTier;
  sourceUrl: string;
  sourceName: string;
  notes: string;
  impactLevel: "HIGH" | "MEDIUM" | "LOW";
  tags: string[];
}

export interface TimelineEvent {
  id: string;
  jurisdiction: Jurisdiction;
  title: string;
  description: string;
  date: string;
  status: Status;
  relatedItemIds: string[];
  priority: number;
}

export const statutoryItems: StatutoryItem[] = [
  // ═══════════════════════════════════════════
  // SINGAPORE — CPF
  // ═══════════════════════════════════════════
  {
    id: "sg-cpf-rate-55below",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Contribution Rates",
    name: "CPF Rate — Age 55 & Below",
    status: "GREEN",
    description: "Total contribution rate for employees aged 55 and below. No change for 2026.",
    currentValue: "37% (Employer 17% + Employee 20%)",
    previousValue: "37%",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates",
    sourceName: "CPF Board",
    notes: "Unchanged since 2016. Applies to wages > $750/month for SC and SPR Year 3+.",
    impactLevel: "LOW",
    tags: ["cpf", "contribution-rate", "stable"],
  },
  {
    id: "sg-cpf-rate-55to60",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Contribution Rates",
    name: "CPF Rate — Age 55 to 60",
    status: "RED",
    description: "Total contribution rate increased from 32.5% to 34% effective 1 Jan 2026. Employer +0.5%, Employee +1%.",
    currentValue: "34% (Employer 16% + Employee 18%)",
    previousValue: "32.5% (Employer 15.5% + Employee 17%)",
    changeType: "rate_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates",
    sourceName: "CPF Board",
    notes: "Part of phased senior worker CPF increase. Extra contributions go to Retirement Account. Further increase to 35.5% confirmed for 2027.",
    impactLevel: "HIGH",
    tags: ["cpf", "contribution-rate", "senior-worker", "2026-change"],
  },
  {
    id: "sg-cpf-rate-60to65",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Contribution Rates",
    name: "CPF Rate — Age 60 to 65",
    status: "RED",
    description: "Total contribution rate increased from 23.5% to 25% effective 1 Jan 2026. Employer +0.5%, Employee +1%.",
    currentValue: "25% (Employer 12.5% + Employee 12.5%)",
    previousValue: "23.5% (Employer 12% + Employee 11.5%)",
    changeType: "rate_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates",
    sourceName: "CPF Board",
    notes: "Further increase to 26% confirmed for 2027 (final step for this age band).",
    impactLevel: "HIGH",
    tags: ["cpf", "contribution-rate", "senior-worker", "2026-change"],
  },
  {
    id: "sg-cpf-rate-65to70",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Contribution Rates",
    name: "CPF Rate — Age 65 to 70",
    status: "GREEN",
    description: "Total contribution rate unchanged at 16.5%.",
    currentValue: "16.5% (Employer 9% + Employee 7.5%)",
    previousValue: "16.5%",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates",
    sourceName: "CPF Board",
    notes: "No change planned for 2027.",
    impactLevel: "LOW",
    tags: ["cpf", "contribution-rate", "stable"],
  },
  {
    id: "sg-cpf-rate-above70",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Contribution Rates",
    name: "CPF Rate — Above 70",
    status: "GREEN",
    description: "Total contribution rate unchanged at 12.5%.",
    currentValue: "12.5% (Employer 7.5% + Employee 5%)",
    previousValue: "12.5%",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates",
    sourceName: "CPF Board",
    notes: "No change planned for 2027.",
    impactLevel: "LOW",
    tags: ["cpf", "contribution-rate", "stable"],
  },
  {
    id: "sg-cpf-ow-ceiling",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Wage Ceilings",
    name: "CPF Ordinary Wage Ceiling",
    status: "RED",
    description: "OW ceiling raised from $7,400 to $8,000/month — the final step of the phased increase since Sep 2023.",
    currentValue: "$8,000/month",
    previousValue: "$7,400/month",
    changeType: "threshold_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates",
    sourceName: "CPF Board",
    notes: "Final step: $6,000 → $6,300 (Sep 2023) → $6,800 (2024) → $7,400 (2025) → $8,000 (2026). No further increases announced.",
    impactLevel: "HIGH",
    tags: ["cpf", "wage-ceiling", "2026-change"],
  },
  {
    id: "sg-cpf-aw-ceiling",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Wage Ceilings",
    name: "CPF Additional Wage Ceiling",
    status: "GREEN",
    description: "AW ceiling formula unchanged: $102,000 minus total OW subject to CPF for the year.",
    currentValue: "$102,000 - Total OW for year",
    previousValue: "$102,000 - Total OW for year",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates",
    sourceName: "CPF Board",
    notes: "Effective AW ceiling is lower with higher OW ceiling ($8,000). Max AW ceiling = $102,000 - $96,000 = $6,000.",
    impactLevel: "MEDIUM",
    tags: ["cpf", "wage-ceiling"],
  },
  {
    id: "sg-cpf-annual-limit",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Wage Ceilings",
    name: "CPF Annual Limit",
    status: "GREEN",
    description: "Annual limit on total employee CPF contributions unchanged at $37,740.",
    currentValue: "$37,740",
    previousValue: "$37,740",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/infohub/news/cpf-related-announcements/new-contribution-rates",
    sourceName: "CPF Board",
    notes: "",
    impactLevel: "LOW",
    tags: ["cpf", "wage-ceiling", "stable"],
  },
  // SG — SHG
  {
    id: "sg-shg-cdac",
    jurisdiction: "SG",
    category: "SHG",
    subcategory: "CDAC",
    name: "CDAC Contribution Rates",
    status: "GREEN",
    description: "Chinese Development Assistance Council rates unchanged. $0.50 to $3.00/month based on wages.",
    currentValue: "$0.50–$3.00/month (5 bands)",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/employer-obligations/contributions-to-self-help-groups",
    sourceName: "CPF Board / CDAC",
    notes: "Employee-borne, SC and SPR only. Opt-out available.",
    impactLevel: "LOW",
    tags: ["shg", "cdac", "stable"],
  },
  {
    id: "sg-shg-ecf",
    jurisdiction: "SG",
    category: "SHG",
    subcategory: "ECF",
    name: "ECF Contribution Rates",
    status: "GREEN",
    description: "Eurasian Community Fund rates unchanged. $2.00 to $20.00/month based on wages.",
    currentValue: "$2.00–$20.00/month (7 bands)",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/employer-obligations/contributions-to-self-help-groups",
    sourceName: "CPF Board",
    notes: "Employee-borne, SC and SPR only.",
    impactLevel: "LOW",
    tags: ["shg", "ecf", "stable"],
  },
  {
    id: "sg-shg-mbmf",
    jurisdiction: "SG",
    category: "SHG",
    subcategory: "MBMF",
    name: "MBMF Contribution Rates",
    status: "GREEN",
    description: "Mosque Building and Mendaki Fund rates unchanged since June 2016. $3.00 to $26.00/month.",
    currentValue: "$3.00–$26.00/month (8 bands)",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2016-06-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.muis.gov.sg/give-back/mbmf/employer-information/",
    sourceName: "MUIS",
    notes: "Only SHG applicable to foreign workers. Includes mosque building and Mendaki components.",
    impactLevel: "LOW",
    tags: ["shg", "mbmf", "stable"],
  },
  {
    id: "sg-shg-sinda",
    jurisdiction: "SG",
    category: "SHG",
    subcategory: "SINDA",
    name: "SINDA Contribution Rates",
    status: "GREEN",
    description: "Singapore Indian Development Association rates unchanged. $1.00 to $30.00/month based on wages.",
    currentValue: "$1.00–$30.00/month (8 bands)",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/employer-obligations/contributions-to-self-help-groups",
    sourceName: "CPF Board",
    notes: "Employee-borne. SC, SPR, and EP holders eligible.",
    impactLevel: "LOW",
    tags: ["shg", "sinda", "stable"],
  },
  // SG — SDL
  {
    id: "sg-sdl",
    jurisdiction: "SG",
    category: "SDL",
    subcategory: "Levy",
    name: "Skills Development Levy",
    status: "GREEN",
    description: "SDL rate unchanged at 0.25% of monthly wages, min $2 max $11.25. Unchanged since October 2008.",
    currentValue: "0.25% (min $2, max $11.25)",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2008-10-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/employer/employer-obligations/skills-development-levy",
    sourceName: "CPF Board / SSG",
    notes: "Employer-borne. Wage cap at $4,500. Applies to all employees including foreign workers.",
    impactLevel: "LOW",
    tags: ["sdl", "levy", "stable"],
  },
  // SG — Filing
  {
    id: "sg-ir8a-filing",
    jurisdiction: "SG",
    category: "Filing",
    subcategory: "IR8A",
    name: "IR8A / AIS Filing",
    status: "AMBER",
    description: "IR8A annual employment income filing. AIS-API 2.0 mandatory since Aug 2025. IR8S form discontinued from YA 2026.",
    currentValue: "AIS-API 2.0 mandatory, deadline 1 Mar 2027 for YA 2026",
    previousValue: "AIS-API 1.0 / paper filing",
    changeType: "system_change",
    effectiveDate: "2025-08-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.iras.gov.sg/taxes/individual-income-tax/employers/auto-inclusion-scheme-(ais)/ais-api-2-0",
    sourceName: "IRAS",
    notes: "IR8S (for excess/voluntary CPF) discontinued. Data now captured within AIS-API 2.0 schema. Paper filing still available for < 5 employees.",
    impactLevel: "HIGH",
    tags: ["filing", "ir8a", "ais", "2025-change"],
  },
  {
    id: "sg-ir21-filing",
    jurisdiction: "SG",
    category: "Filing",
    subcategory: "IR21",
    name: "IR21 Tax Clearance",
    status: "GREEN",
    description: "IR21 filing for cessation of non-citizen/SPR employees. No changes to process or deadlines.",
    currentValue: "File within 1 month before cessation date",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.iras.gov.sg/taxes/individual-income-tax/employers/tax-clearance-for-foreign-spr-employees/overview",
    sourceName: "IRAS",
    notes: "Must withhold monies due until tax clearance directive received. Applies to non-SC/SPR employees only.",
    impactLevel: "LOW",
    tags: ["filing", "ir21", "tax-clearance"],
  },
  // SG — Future Changes
  {
    id: "sg-cpf-2027-55to60",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Future Changes",
    name: "2027 CPF Rate — Age 55 to 60",
    status: "AMBER",
    description: "Confirmed increase to 35.5% total (Employer 16.5% + Employee 19%) from 1 Jan 2027.",
    currentValue: "35.5% (planned from 1 Jan 2027)",
    previousValue: "34% (current 2026)",
    changeType: "rate_change",
    effectiveDate: "2027-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/service/article/what-are-the-changes-to-the-cpf-contribution-rates-for-senior-workers-that-will-take-effect-from-1-january-2027",
    sourceName: "CPF Board",
    notes: "Officially confirmed. CPF Transition Offset (CTO) for employers will apply.",
    impactLevel: "HIGH",
    tags: ["cpf", "future-change", "2027"],
  },
  {
    id: "sg-cpf-2027-60to65",
    jurisdiction: "SG",
    category: "CPF",
    subcategory: "Future Changes",
    name: "2027 CPF Rate — Age 60 to 65",
    status: "AMBER",
    description: "Confirmed increase to 26% total (Employer 13% + Employee 13%) from 1 Jan 2027. Final step for this band.",
    currentValue: "26% (planned from 1 Jan 2027)",
    previousValue: "25% (current 2026)",
    changeType: "rate_change",
    effectiveDate: "2027-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.cpf.gov.sg/service/article/what-are-the-changes-to-the-cpf-contribution-rates-for-senior-workers-that-will-take-effect-from-1-january-2027",
    sourceName: "CPF Board",
    notes: "Final planned increase for this age band. Target rate reached.",
    impactLevel: "HIGH",
    tags: ["cpf", "future-change", "2027"],
  },

  // ═══════════════════════════════════════════
  // HONG KONG — MPF
  // ═══════════════════════════════════════════
  {
    id: "hk-mpf-rate",
    jurisdiction: "HK",
    category: "MPF",
    subcategory: "Contribution Rates",
    name: "MPF Contribution Rate",
    status: "GREEN",
    description: "Mandatory contribution rate unchanged: 5% employer + 5% employee on relevant income.",
    currentValue: "10% total (5% + 5%)",
    previousValue: "10%",
    changeType: "no_change",
    effectiveDate: "2000-12-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.mpfa.org.hk/en/mpf-system/mandatory-contributions/employee",
    sourceName: "MPFA",
    notes: "Unchanged since MPF inception in December 2000.",
    impactLevel: "LOW",
    tags: ["mpf", "contribution-rate", "stable"],
  },
  {
    id: "hk-mpf-min-ri",
    jurisdiction: "HK",
    category: "MPF",
    subcategory: "Thresholds",
    name: "MPF Minimum Relevant Income",
    status: "GREEN",
    description: "Monthly minimum relevant income threshold unchanged at $7,100. Below this, employee contributes nil.",
    currentValue: "HK$7,100/month",
    previousValue: "HK$7,100/month",
    changeType: "no_change",
    effectiveDate: "2013-11-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.mpfa.org.hk/en/mpf-system/mandatory-contributions/employee",
    sourceName: "MPFA",
    notes: "Unchanged since Nov 2013. Employee earning below $7,100 pays no employee contribution; employer still pays 5%.",
    impactLevel: "LOW",
    tags: ["mpf", "threshold", "stable"],
  },
  {
    id: "hk-mpf-max-ri",
    jurisdiction: "HK",
    category: "MPF",
    subcategory: "Thresholds",
    name: "MPF Maximum Relevant Income",
    status: "GREEN",
    description: "Monthly maximum relevant income cap unchanged at HK$30,000. Contributions capped at $1,500 each.",
    currentValue: "HK$30,000/month",
    previousValue: "HK$30,000/month",
    changeType: "no_change",
    effectiveDate: "2014-06-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.mpfa.org.hk/en/mpf-system/mandatory-contributions/employee",
    sourceName: "MPFA",
    notes: "Unchanged since Jun 2014. Max employer + employee contribution = HK$3,000/month total.",
    impactLevel: "LOW",
    tags: ["mpf", "threshold", "stable"],
  },
  {
    id: "hk-mpf-offset-abolish",
    jurisdiction: "HK",
    category: "MPF",
    subcategory: "Offsetting",
    name: "MPF Offsetting Abolished",
    status: "RED",
    description: "Employer MPF contributions can no longer offset severance/long-service payments for employment on or after 1 May 2025.",
    currentValue: "Abolished for post-1 May 2025 employment",
    previousValue: "Offsetting permitted",
    changeType: "abolished",
    effectiveDate: "2025-05-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.mpfa.org.hk/en/mpf-system/abolition-of-mpf-offsetting",
    sourceName: "MPFA",
    notes: "Transition: Pre-1 May 2025 employment still allows offsetting under old rules. Dual-calculation required for transition employees.",
    impactLevel: "HIGH",
    tags: ["mpf", "offsetting", "2025-change", "critical"],
  },
  {
    id: "hk-empf-migration",
    jurisdiction: "HK",
    category: "MPF",
    subcategory: "eMPF",
    name: "eMPF Platform Migration",
    status: "AMBER",
    description: "eMPF digital platform migration ongoing. BCT InvestSmart target 26 Mar 2026, BEA IS target 30 Apr 2026.",
    currentValue: "15/17 schemes onboarded; 2 pending",
    previousValue: "Partial migration",
    changeType: "system_change",
    effectiveDate: "2026-03-26",
    confidenceTier: "Tier 2",
    sourceUrl: "https://www.empf.org.hk/en/about-empf/latest-news",
    sourceName: "eMPF Platform Company Limited",
    notes: "After full onboarding, employers will manage MPF contributions through the centralized eMPF portal.",
    impactLevel: "MEDIUM",
    tags: ["mpf", "empf", "migration", "2026-change"],
  },
  {
    id: "hk-mpf-full-portability",
    jurisdiction: "HK",
    category: "MPF",
    subcategory: "eMPF",
    name: "MPF Full Portability — Phase 1",
    status: "AMBER",
    description: "Full portability of employer MPF contributions expected within 2026. Exact date TBA.",
    currentValue: "Phase 1 expected H2 2026 (date TBA)",
    previousValue: "No portability",
    changeType: "new_rule",
    effectiveDate: "2026-12-31",
    confidenceTier: "Tier 2",
    sourceUrl: "https://www.mpfa.org.hk/en/mpf-system/empf-platform",
    sourceName: "MPFA",
    notes: "GAP ITEM: Exact effective date not yet gazetted. Phase 1 allows transfer of employer contributions between schemes.",
    impactLevel: "HIGH",
    tags: ["mpf", "portability", "gap-item", "2026-change"],
  },
  // HK — Filing
  {
    id: "hk-ir56b-filing",
    jurisdiction: "HK",
    category: "Filing",
    subcategory: "IR56B",
    name: "IR56B Annual Filing",
    status: "GREEN",
    description: "Annual employer return of remuneration. No changes to format or deadline for YA 2025/26.",
    currentValue: "File within 1 month of issue date on BIR56A",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-04-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.ird.gov.hk/eng/tax/ere.htm",
    sourceName: "IRD Hong Kong",
    notes: "BIR56A typically issued 1 April. eFiling available via eTAX.",
    impactLevel: "LOW",
    tags: ["filing", "ir56b", "annual"],
  },
  {
    id: "hk-ir56-xml-specs",
    jurisdiction: "HK",
    category: "Filing",
    subcategory: "IR56E/G/M",
    name: "IR56E/G/M New XML Specs",
    status: "AMBER",
    description: "New XML specifications for IR56E (commencement), IR56G (departure), IR56M (non-employee) from Jul 2025.",
    currentValue: "New XML schema mandatory for eFiling",
    previousValue: "Old format",
    changeType: "filing_change",
    effectiveDate: "2025-07-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.ird.gov.hk/eng/tax/ere_efiling.htm",
    sourceName: "IRD Hong Kong",
    notes: "Storage device submission banned since Apr 2024. Paper or eFiling only.",
    impactLevel: "MEDIUM",
    tags: ["filing", "ir56", "xml", "2025-change"],
  },

  // ═══════════════════════════════════════════
  // MALAYSIA — EPF
  // ═══════════════════════════════════════════
  {
    id: "my-epf-rate-below60",
    jurisdiction: "MY",
    category: "EPF",
    subcategory: "Contribution Rates",
    name: "EPF Rate — Below Age 60 (Malaysian)",
    status: "GREEN",
    description: "Employer 12%/13% + Employee 11% unchanged. 13% applies to wages ≤ RM5,000.",
    currentValue: "Employer 13% (≤RM5K) / 12% (>RM5K) + Employee 11%",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.kwsp.gov.my/employer/contribution/rate-of-contribution",
    sourceName: "KWSP/EPF",
    notes: "Third Schedule, Part A. Rate restored to 11% employee from temporary 9% COVID reduction.",
    impactLevel: "LOW",
    tags: ["epf", "contribution-rate", "stable"],
  },
  {
    id: "my-epf-rate-above60",
    jurisdiction: "MY",
    category: "EPF",
    subcategory: "Contribution Rates",
    name: "EPF Rate — Age 60+ (Malaysian)",
    status: "GREEN",
    description: "Employer 4% + Employee 0% for members 60 and above. Voluntary employee contribution allowed.",
    currentValue: "Employer 4% + Employee 0% (voluntary allowed)",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.kwsp.gov.my/employer/contribution/rate-of-contribution",
    sourceName: "KWSP/EPF",
    notes: "Third Schedule, Part E (age 60+). Employee may elect higher contribution.",
    impactLevel: "LOW",
    tags: ["epf", "contribution-rate", "stable"],
  },
  {
    id: "my-epf-foreign-mandatory",
    jurisdiction: "MY",
    category: "EPF",
    subcategory: "Foreign Workers",
    name: "EPF Foreign Workers — Mandatory",
    status: "RED",
    description: "From Oct 2025, foreign workers mandatory EPF: Employer 2% + Employee 2% (Part F schedule).",
    currentValue: "Employer 2% + Employee 2% (mandatory from Oct 2025)",
    previousValue: "Voluntary / RM5 employer only",
    changeType: "new_rule",
    effectiveDate: "2025-10-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.kwsp.gov.my/employer/contribution/rate-of-contribution",
    sourceName: "KWSP/EPF",
    notes: "Part F of Third Schedule. Applies to all foreign workers with valid work permits. Previously employer paid flat RM5.",
    impactLevel: "HIGH",
    tags: ["epf", "foreign-worker", "2025-change", "critical"],
  },
  // MY — SOCSO
  {
    id: "my-socso-rate",
    jurisdiction: "MY",
    category: "SOCSO",
    subcategory: "Contribution Rates",
    name: "SOCSO Contribution Rate",
    status: "GREEN",
    description: "Employment Injury + Invalidity: Employer ~1.75% + Employee ~0.5% (per wage-band table).",
    currentValue: "Per SOCSO contribution table (wage-band based)",
    previousValue: "No change to rates",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.perkeso.gov.my/en/contribution-rate.html",
    sourceName: "PERKESO/SOCSO",
    notes: "Contribution is per wage-band table, not a flat percentage. Both Employment Injury and Invalidity schemes.",
    impactLevel: "LOW",
    tags: ["socso", "contribution-rate", "stable"],
  },
  {
    id: "my-socso-wage-ceiling",
    jurisdiction: "MY",
    category: "SOCSO",
    subcategory: "Wage Ceiling",
    name: "SOCSO/EIS Wage Ceiling",
    status: "RED",
    description: "SOCSO and EIS wage ceiling raised from RM5,000 to RM6,000 effective October 2024.",
    currentValue: "RM6,000/month",
    previousValue: "RM5,000/month",
    changeType: "threshold_change",
    effectiveDate: "2024-10-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.perkeso.gov.my/en/contribution-rate.html",
    sourceName: "PERKESO/SOCSO",
    notes: "Applies to both SOCSO and EIS. Employees earning > RM6,000 contribute on first RM6,000 only.",
    impactLevel: "HIGH",
    tags: ["socso", "eis", "wage-ceiling", "2024-change"],
  },
  {
    id: "my-socso-foreign-invalidity",
    jurisdiction: "MY",
    category: "SOCSO",
    subcategory: "Foreign Workers",
    name: "SOCSO Invalidity — Foreign Workers",
    status: "AMBER",
    description: "Invalidity pension scheme extended to foreign workers from July 2024.",
    currentValue: "Foreign workers now covered under both EI + Invalidity",
    previousValue: "Employment Injury only",
    changeType: "new_rule",
    effectiveDate: "2024-07-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.perkeso.gov.my/en/employer/foreign-worker.html",
    sourceName: "PERKESO/SOCSO",
    notes: "Previously foreign workers only covered for Employment Injury. Now full SOCSO coverage applies.",
    impactLevel: "MEDIUM",
    tags: ["socso", "foreign-worker", "2024-change"],
  },
  // MY — EIS
  {
    id: "my-eis-rate",
    jurisdiction: "MY",
    category: "EIS",
    subcategory: "Contribution Rates",
    name: "EIS Contribution Rate",
    status: "GREEN",
    description: "Employment Insurance System: Employer 0.2% + Employee 0.2%. Wage ceiling RM6,000.",
    currentValue: "0.4% total (0.2% + 0.2%), ceiling RM6,000",
    previousValue: "No change to rate",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.perkeso.gov.my/en/sip.html",
    sourceName: "PERKESO/SOCSO",
    notes: "Wage ceiling increased to RM6,000 (same as SOCSO) in Oct 2024. Rate itself unchanged.",
    impactLevel: "LOW",
    tags: ["eis", "contribution-rate", "stable"],
  },
  // MY — LINDUNG
  {
    id: "my-lindung247",
    jurisdiction: "MY",
    category: "SOCSO",
    subcategory: "LINDUNG 24/7",
    name: "LINDUNG 24/7 — Social Protection",
    status: "AMBER",
    description: "24/7 social protection scheme passed Parliament Dec 2025. Expected enforcement mid-2026. Not yet gazetted.",
    currentValue: "Awaiting gazette (passed Parliament Dec 2025)",
    previousValue: "N/A — new scheme",
    changeType: "new_rule",
    effectiveDate: "2026-06-30",
    confidenceTier: "Tier 2",
    sourceUrl: "https://www.perkeso.gov.my/en/",
    sourceName: "PERKESO/SOCSO",
    notes: "GAP ITEM: Passed Parliament but not yet gazetted. Will extend SOCSO-like coverage to 24/7 (not just during work). Contribution rates TBA.",
    impactLevel: "HIGH",
    tags: ["socso", "lindung", "new-scheme", "gap-item", "2026-change"],
  },
  // MY — PCB/MTD
  {
    id: "my-pcb-mtd",
    jurisdiction: "MY",
    category: "PCB/MTD",
    subcategory: "Tax Deduction",
    name: "PCB/MTD Monthly Tax Deduction",
    status: "GREEN",
    description: "Monthly Tax Deduction (PCB) calculation formula unchanged for 2026. Budget 2026 TP1 relief changes affect amounts.",
    currentValue: "Standard MTD formula (LHDN Schedule)",
    previousValue: "No formula change",
    changeType: "no_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.hasil.gov.my/en/employers/",
    sourceName: "LHDN/IRBM",
    notes: "Budget 2026 changed individual relief categories (C1, C4, C8, C11, C15-C17) affecting MTD computation amounts, but the formula itself is unchanged.",
    impactLevel: "MEDIUM",
    tags: ["pcb", "mtd", "tax-deduction"],
  },
  {
    id: "my-budget2026-tp1",
    jurisdiction: "MY",
    category: "PCB/MTD",
    subcategory: "Budget 2026 TP1",
    name: "Budget 2026 — TP1 Relief Changes",
    status: "RED",
    description: "Budget 2026 introduced changes to individual tax relief categories: C1, C4, C8, C11, C15-C17.",
    currentValue: "Updated relief amounts for YA 2026",
    previousValue: "YA 2025 amounts",
    changeType: "rate_change",
    effectiveDate: "2026-01-01",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.hasil.gov.my/en/",
    sourceName: "LHDN/IRBM",
    notes: "Affects MTD computation. Employees submitting TP1 forms with updated relief amounts will have different PCB deductions.",
    impactLevel: "MEDIUM",
    tags: ["pcb", "budget-2026", "tax-relief", "2026-change"],
  },
  // MY — Filing
  {
    id: "my-ea-form",
    jurisdiction: "MY",
    category: "Filing",
    subcategory: "EA Form",
    name: "EA Form (Employee)",
    status: "GREEN",
    description: "Employer must provide EA form to employees by end of February. No format changes for YA 2025.",
    currentValue: "Deadline: 28 Feb 2026 (for YA 2025)",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-02-28",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.hasil.gov.my/en/employers/",
    sourceName: "LHDN/IRBM",
    notes: "EA form shows annual remuneration summary. Must be provided to all employees.",
    impactLevel: "LOW",
    tags: ["filing", "ea-form", "annual"],
  },
  {
    id: "my-e-form",
    jurisdiction: "MY",
    category: "Filing",
    subcategory: "E Form",
    name: "E Form (Employer Return)",
    status: "AMBER",
    description: "Employer annual return. Deadline 31 March 2026 for YA 2025. e-Filing mandatory.",
    currentValue: "Deadline: 31 Mar 2026 (for YA 2025)",
    previousValue: "No change",
    changeType: "no_change",
    effectiveDate: "2026-03-31",
    confidenceTier: "Tier 1",
    sourceUrl: "https://www.hasil.gov.my/en/employers/",
    sourceName: "LHDN/IRBM",
    notes: "UPCOMING DEADLINE. Must include details of all employees and remuneration paid during the year.",
    impactLevel: "MEDIUM",
    tags: ["filing", "e-form", "annual", "deadline-approaching"],
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: "tl-1",
    jurisdiction: "MY",
    title: "EA Form Deadline",
    description: "Provide EA forms to all employees for YA 2025",
    date: "2026-02-28",
    status: "RED",
    relatedItemIds: ["my-ea-form"],
    priority: 1,
  },
  {
    id: "tl-2",
    jurisdiction: "HK",
    title: "eMPF — BCT InvestSmart Onboarding",
    description: "BCT InvestSmart scheme migrates to eMPF platform",
    date: "2026-03-26",
    status: "AMBER",
    relatedItemIds: ["hk-empf-migration"],
    priority: 2,
  },
  {
    id: "tl-3",
    jurisdiction: "MY",
    title: "E Form Filing Deadline",
    description: "Employer annual return (Form E) for YA 2025 due",
    date: "2026-03-31",
    status: "RED",
    relatedItemIds: ["my-e-form"],
    priority: 1,
  },
  {
    id: "tl-4",
    jurisdiction: "HK",
    title: "IR56B Filing Period Opens",
    description: "BIR56A typically issued; IR56B due within 1 month",
    date: "2026-04-01",
    status: "AMBER",
    relatedItemIds: ["hk-ir56b-filing"],
    priority: 3,
  },
  {
    id: "tl-5",
    jurisdiction: "HK",
    title: "eMPF — BEA IS Onboarding",
    description: "BEA InvestSmart scheme migrates to eMPF platform",
    date: "2026-04-30",
    status: "AMBER",
    relatedItemIds: ["hk-empf-migration"],
    priority: 2,
  },
  {
    id: "tl-6",
    jurisdiction: "MY",
    title: "LINDUNG 24/7 Expected Enforcement",
    description: "New 24/7 social protection scheme expected to take effect (date TBA)",
    date: "2026-06-30",
    status: "AMBER",
    relatedItemIds: ["my-lindung247"],
    priority: 2,
  },
  {
    id: "tl-7",
    jurisdiction: "HK",
    title: "MPF Full Portability — Phase 1",
    description: "Employee choice of employer MPF scheme expected to launch",
    date: "2026-12-31",
    status: "AMBER",
    relatedItemIds: ["hk-mpf-full-portability"],
    priority: 2,
  },
  {
    id: "tl-8",
    jurisdiction: "SG",
    title: "CPF Senior Worker Rate Increase",
    description: "Ages 55-60: 35.5%, Ages 60-65: 26%. Confirmed.",
    date: "2027-01-01",
    status: "AMBER",
    relatedItemIds: ["sg-cpf-2027-55to60", "sg-cpf-2027-60to65"],
    priority: 1,
  },
  {
    id: "tl-9",
    jurisdiction: "SG",
    title: "IR8A/AIS Filing Deadline (YA 2026)",
    description: "AIS-API 2.0 submission for Year of Assessment 2026",
    date: "2027-03-01",
    status: "AMBER",
    relatedItemIds: ["sg-ir8a-filing"],
    priority: 3,
  },
];
